app.dlc.version-required = 100
app.dlc.version-optional = 1
app.support.email-address = customer.support@venan.com
app.support.email-subject = Ninjatown: Trees Of Doom! Support Request
app.support.email-body = \n\nAndroid Version: %s\nAndroid SDK: %i\nDevice Manufacturer: %s\nDevice Model: %s\nBuild Fingerprint: %s\nApplication Version: %s\nVenan Id: %lli\nCharacter Id: %i
app.shawnimals.shop-url = http://shop.shawnimals.com/collections/ninjatown-trees-of-doom
app.newsfeed.url = http://venan.s3.amazonaws.com/newsfeed/treesofdoom_prod.xml
app.moregames.url = http://venan.com/treesofdoom/
app.android.android-market-url = market://details?id=com.venan.treesofdoom
app.facebook.link = http://venanarcade.com/ninjatown_info.php
app.facebook.picture = http://www.venanarcade.com/promo/climber/icon_fb_128.png
app.facebook.appkey = 106421882714309
